// <auto-generated />
using System;
using SalesOrderService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SalesOrderService.Migrations
{
    [DbContext(typeof(SalesOrderContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesOrderService.Models.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OdataContext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("SalesOrderService.Models.SalesOrderTestPoco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArePricesIncludingSalesTax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreTotalsCalculated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankConstantSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankSpecificSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("BaseDocumentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("BaseDocumentItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BaseDocumentLineNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseDocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseDocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CFPSCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIPEcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CashDiscountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeCustomerGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommissionCustomerGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommissionSalesRepresentativeGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ConfirmedReceiptDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ConfirmedShippingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContactPersonId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditNoteReasonCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPaymentFinancialInterestCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPaymentFineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPaymentMethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPaymentMethodSpecificationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPostingProfileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerRequisitionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerTransactionSettlementType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomersOrderReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataAreaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultLedgerDimensionDisplayValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultShippingSiteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultShippingWarehouseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressCityInKana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressCountryRegionISOCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressCountryRegionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressCountyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressDistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressDunsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeliveryAddressLatitude")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryAddressLocationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeliveryAddressLongitude")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryAddressName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressPostBox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressStateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressStreetInKana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressStreetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeliveryAddressTimeZone")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("DeliveryAddressZipCode")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryBuildingCompliment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeliveryModeCode")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryReasonCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryTermsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectDebitMandateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EInvoiceDimensionAccountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EUSalesListCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExportReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FiscalDocumentOperationTypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FiscalOperationPresenceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("FixedDueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("FixedExchangeRate")
                        .HasColumnType("bigint");

                    b.Property<string>("FormattedDelveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormattedInvoiceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FulfillmentPolicyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullRunCTPStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntrastatPortId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntrastatStatisticsProcedureCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntrastatTransactionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntrastatTransportModeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryReservationMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCityInKana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCountryRegionISOCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCountryRegionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCountyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressDistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InvoiceAddressLatitude")
                        .HasColumnType("bigint");

                    b.Property<long?>("InvoiceAddressLongitude")
                        .HasColumnType("bigint");

                    b.Property<string>("InvoiceAddressPostBox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStreetInKana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStreetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("InvoiceAddressTimeZone")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InvoiceAddressZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceBuildingCompliment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceCustomerAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoicePaymentAttachmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsConsolidatedInvoiceTarget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsDeliveryAddressOrderSpecific")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsDeliveryAddressPrivate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsEInvoiceDimensionAccountCodeSpecifiedPerLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsEntryCertificateRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsExportSale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsFinalUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsInvoiceAddressPrivate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsOneTimeCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsOwnEntryCertificateIssued")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsSalesProcessingStopped")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsServiceDeliveryAddressBased")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineDiscountCustomerGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MultilineDiscountCustomerGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberSequenceGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdataContext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdataEtag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("OrderCreationDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("OrderHeaderTaxAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderOrAgreementCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderResponsiblePersonnelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderTakerPersonnelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrderTotalAmount")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderTotalChargesAmount")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderTotalDiscountAmount")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderTotalTaxAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderingCustomerAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverrideSalesTax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentScheduleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PaymentTermsBaseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaymentTermsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceCustomerGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuotationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReportingCurrencyFixedExchangeRate")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RequestedReceiptDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RequestedShippingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevRecContractEndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevRecContractStartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RevRecFollowOriginalPricingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RevRecLatestReverseJournal")
                        .HasColumnType("bigint");

                    b.Property<string>("RevRecMultipleSOReallocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevRecReallocationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderOriginCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderPoolId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderProcessingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderPromisingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesRebateCustomerGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesTaxGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesUnitId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceFiscalInformationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCarrierCustomerAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCarrierId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCarrierServiceGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCarrierServiceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkipCreateAutoCharges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkipGlobalUnifiedPricingCalculation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubBillCreatedFromSubscriptionBilling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMACustomerGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxExemptNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPartySalesDigitalPlatform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPartySalesDigitalPlatformCNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TotalDiscountAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("TotalDiscountCustomerGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TotalDiscountPercentage")
                        .HasColumnType("bigint");

                    b.Property<string>("TransportationBrokerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TransportationDocumentLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransportationModeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportationRoutePlanId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportationTemplateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WillAutomaticInventoryReservationConsiderBatchAttributes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SalesOrderTestPoco");
                });

            modelBuilder.Entity("SalesOrderService.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArePricesIncludingSalesTax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreTotalsCalculated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankConstantSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankSpecificSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("BaseDocumentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("BaseDocumentItemNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BaseDocumentLineNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseDocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseDocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CashDiscountCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CfpsCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeCustomerGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CipEcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommissionCustomerGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommissionSalesRepresentativeGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ConfirmedReceiptDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ConfirmedShippingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContactPersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContentId")
                        .HasColumnType("int");

                    b.Property<string>("CreditNoteReasonCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPaymentFinancialInterestCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPaymentFineCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPaymentMethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPaymentMethodSpecificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPostingProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerRequisitionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerTransactionSettlementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomersOrderReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataAreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultLedgerDimensionDisplayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultShippingSiteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultShippingWarehouseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressCityInKana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressCountryRegionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressCountryRegionIsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressCountyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressDistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressDunsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DeliveryAddressLatitude")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryAddressLocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DeliveryAddressLongitude")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryAddressName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressPostBox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressStateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressStreetInKana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressStreetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DeliveryAddressTimeZone")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeliveryAddressZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryBuildingCompliment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DeliveryModeCode")
                        .HasColumnType("bigint");

                    b.Property<string>("DeliveryReasonCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryTermsCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectDebitMandateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EInvoiceDimensionAccountCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EuSalesListCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExportReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FiscalDocumentOperationTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FiscalOperationPresenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FixedDueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("FixedExchangeRate")
                        .HasColumnType("bigint");

                    b.Property<string>("FormattedDelveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormattedInvoiceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FulfillmentPolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullRunCtpStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntrastatPortId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntrastatStatisticsProcedureCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntrastatTransactionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntrastatTransportModeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryReservationMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCityInKana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCountryRegionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCountryRegionIsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCountyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressDistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("InvoiceAddressLatitude")
                        .HasColumnType("bigint");

                    b.Property<long>("InvoiceAddressLongitude")
                        .HasColumnType("bigint");

                    b.Property<string>("InvoiceAddressPostBox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStreetInKana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStreetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("InvoiceAddressTimeZone")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InvoiceAddressZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceBuildingCompliment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceCustomerAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoicePaymentAttachmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsConsolidatedInvoiceTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsDeliveryAddressOrderSpecific")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsDeliveryAddressPrivate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsEInvoiceDimensionAccountCodeSpecifiedPerLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsEntryCertificateRequired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsExportSale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsFinalUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsInvoiceAddressPrivate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsOneTimeCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsOwnEntryCertificateIssued")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsSalesProcessingStopped")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsServiceDeliveryAddressBased")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineDiscountCustomerGroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MultilineDiscountCustomerGroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberSequenceGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdataEtag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OrderCreationDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("OrderHeaderTaxAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderOrAgreementCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderResponsiblePersonnelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderTakerPersonnelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrderTotalAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderTotalChargesAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderTotalDiscountAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderTotalTaxAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderingCustomerAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverrideSalesTax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentScheduleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("PaymentTermsBaseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaymentTermsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceCustomerGroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuotationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ReportingCurrencyFixedExchangeRate")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RequestedReceiptDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RequestedShippingDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RevRecContractEndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RevRecContractStartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RevRecFollowOriginalPricingMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RevRecLatestReverseJournal")
                        .HasColumnType("bigint");

                    b.Property<string>("RevRecMultipleSoReallocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevRecReallocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderOriginCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderPoolId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderProcessingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderPromisingMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesRebateCustomerGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesTaxGroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesUnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceFiscalInformationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCarrierCustomerAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCarrierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCarrierServiceGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCarrierServiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkipCreateAutoCharges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkipGlobalUnifiedPricingCalculation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubBillCreatedFromSubscriptionBilling")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxExemptNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPartySalesDigitalPlatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPartySalesDigitalPlatformCnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TmaCustomerGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TotalDiscountAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("TotalDiscountCustomerGroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TotalDiscountPercentage")
                        .HasColumnType("bigint");

                    b.Property<string>("TransportationBrokerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TransportationDocumentLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransportationModeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportationRoutePlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportationTemplateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WillAutomaticInventoryReservationConsiderBatchAttributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.ToTable("Value");
                });

            modelBuilder.Entity("SalesOrderService.Models.Value", b =>
                {
                    b.HasOne("SalesOrderService.Models.Content", null)
                        .WithMany("Value")
                        .HasForeignKey("ContentId");
                });

            modelBuilder.Entity("SalesOrderService.Models.Content", b =>
                {
                    b.Navigation("Value");
                });
#pragma warning restore 612, 618
        }
    }
}
