// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesInvoiceHeaderService;

#nullable disable

namespace SalesInvoiceHeadersService.Migrations
{
    [DbContext(typeof(SalesInvoiceHeadersContext))]
    partial class SalesInvoiceHeadersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesInvoiceHeaderService.CustInvoiceJour", b =>
                {
                    b.Property<long?>("RecId1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("RecId1"));

                    b.Property<decimal?>("AmountMST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContactPersonId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomersOrderReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryModeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryTermsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DemandDateJour")
                        .HasColumnType("datetime");

                    b.Property<string>("DriverCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRNNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCountryRegionISOCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCountryRegionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStreetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceCustomerAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("InvoiceHeaderTaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceId_CT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsProcess_CT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsProcessed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsReturn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsSample")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedgerVoucher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime1")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PORefID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTermsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnReasonCodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesId_CT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderOriginCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderResponsiblePersonnelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalespersonCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorCodeBak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalChargeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDiscountCustomerGroupCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalInvoiceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalTaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VehicleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataAreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecId1");

                    b.ToTable("CustInvoiceJour");
                });

            modelBuilder.Entity("SalesInvoiceHeaderService.CustInvoiceJourTestR", b =>
                {
                    b.Property<long?>("RecId1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("RecId1"));

                    b.Property<decimal?>("AmountMST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContactPersonId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomersOrderReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddressName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryModeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryTermsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DemandDateJour")
                        .HasColumnType("datetime");

                    b.Property<string>("DriverCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IRNNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCountryRegionISOCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressCountryRegionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressStreetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddressZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceCustomerAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("InvoiceHeaderTaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceId_CT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsProcess_CT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsProcessed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsReturn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsSample")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedgerVoucher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime1")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PORefID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTermsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnReasonCodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesId_CT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderOriginCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderResponsiblePersonnelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalespersonCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorCodeBak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalChargeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDiscountCustomerGroupCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalInvoiceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalTaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VehicleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataAreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecId1");

                    b.ToTable("CustInvoiceJourTestR");
                });
#pragma warning restore 612, 618
        }
    }
}
